version: "3.8"
name: 'we-space'
services:
  postgres:
    image: postgres:14
    container_name: db_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_FOLDER}/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - "3001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ${DATA_FOLDER}/pgadmin:/var/lib/pgadmin

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - "3002:8080"

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ${DATA_FOLDER}/redis:/bitnami/redis/data
